data_pipelines = {
    'psg-32-identical': {
        'context_range': 'paragraph',
        'max_context_len': 32,
        'min_dq_len': 8,
        'min_q_len': 1,
        'max_q_len': 1,
        'min_d_len': 1,
        'max_d_len': 1,
        'word_del_ratio': 0,
        'query_in_doc': True,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
    },
    'psg-Q16D64-notitle': {
        'context_range': 'paragraph',
        'max_context_len': 256,
        'min_dq_len': 8,
        'min_q_len': 16,
        'max_q_len': 1,
        'min_d_len': 1,
        'max_d_len': 1,
        'word_del_ratio': 0,
        'query_in_doc': True,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
    },
    'psg-QD128-notitle': {
        'context_range': 'paragraph',
        'max_context_len': 128,
        'min_dq_len': 8,
        'min_q_len': 8,
        'max_q_len': 128,
        'min_d_len': 8,
        'max_d_len': 128,
        'word_del_ratio': 0,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
    },
    'sec-QD256-notitle': {
        'context_range': 'section',
        'max_context_len': 256,
        'min_dq_len': 8,
        'min_q_len': 8,
        'max_q_len': 256,
        'min_d_len': 8,
        'max_d_len': 256,
        'word_del_ratio': 0,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
    },
    'sec-QD128-notitle': {
        'context_range': 'section',
        'max_context_len': 128,
        'min_dq_len': 8,
        'min_q_len': 8,
        'max_q_len': 128,
        'min_d_len': 8,
        'max_d_len': 128,
        'word_del_ratio': 0,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
    },
    'doc-QD256-notitle': {
        'context_range': 'document',
        'max_context_len': 256,
        'min_dq_len': 8,
        'min_q_len': 8,
        'max_q_len': 256,
        'min_d_len': 8,
        'max_d_len': 256,
        'word_del_ratio': 0,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
    },
    'doc-QD128-notitle': {
        'context_range': 'document',
        'max_context_len': 128,
        'min_dq_len': 8,
        'min_q_len': 8,
        'max_q_len': 128,
        'min_d_len': 8,
        'max_d_len': 128,
        'word_del_ratio': 0,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
    },
    'contriever-256': {
        'context_range': 'document',
        'max_context_len': 256,
        'min_dq_len': 8,
        'min_q_len': 0.05,
        'max_q_len': 0.5,
        'min_d_len': 0.05,
        'max_d_len': 0.5,
        'word_del_ratio': 0.1,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
    },
    'doc-QD256-notitle+nbr': {
        'context_range': 'document',
        'max_context_len': 256,
        'min_dq_len': 8,
        'min_q_len': 8,
        'max_q_len': 256,
        'min_d_len': 8,
        'max_d_len': 256,
        'word_del_ratio': 0,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
        'include_nbr_negative': True,
        'include_title2ctx': False,
    },
    'doc-QD256-notitle+nbr+title2ctx': {
        'context_range': 'document',
        'max_context_len': 256,
        'min_dq_len': 8,
        'min_q_len': 8,
        'max_q_len': 256,
        'min_d_len': 8,
        'max_d_len': 256,
        'word_del_ratio': 0,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
        'include_nbr_negative': True,
        'include_title2ctx': True,
    },
    'sec-QD256-notitle+nbr+title2ctx': {
        'context_range': 'section',
        'max_context_len': 256,
        'min_dq_len': 8,
        'min_q_len': 8,
        'max_q_len': 256,
        'min_d_len': 8,
        'max_d_len': 256,
        'word_del_ratio': 0,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
        'include_nbr_negative': True,
        'include_title2ctx': True,
    },
    'psg-QD256-notitle+nbr+title2ctx': {
        'context_range': 'paragraph',
        'max_context_len': 256,
        'min_dq_len': 8,
        'min_q_len': 8,
        'max_q_len': 256,
        'min_d_len': 8,
        'max_d_len': 256,
        'word_del_ratio': 0,
        'query_in_doc': False,
        'q_retain_ratio': 1,
        'include_doctitle_ratio': 0.0,
        'include_nbr_negative': True,
        'include_title2ctx': True,
    },
}

def load_data_config(data_args):
    # prepare for data loader
    if data_args.data_pipeline_name:
        data_prep_config = data_pipelines[data_args.data_pipeline_name]
        print('Using pre-defined data pipeline: ' + str(data_args.data_pipeline_name))
    else:
        data_prep_config = {
            'max_context_len': data_args.max_context_len,
            'min_dq_len': data_args.min_dq_len,
            'min_q_len': data_args.min_q_len,
            'max_q_len': data_args.max_q_len,
            'min_d_len': data_args.min_d_len,
            'max_d_len': data_args.max_d_len,
            'word_del_ratio': data_args.word_del_ratio,
            'query_in_doc': data_args.query_in_doc,
            'q_retain_ratio': data_args.q_retain_ratio,
            'context_range': data_args.context_range,
            'include_doctitle_ratio': data_args.include_doctitle_ratio,
        }
    print('Data loading parameters:')
    for k, v in data_prep_config.items():
        setattr(data_args, k, v)
        print(f'\t\t{k} = {v}')

    return data_prep_config